/**
 * English language patterns for prompt anatomy detection
 * Converted from backend/data/multilingual_patterns.yaml
 */

export const englishPatterns = {
  role: [
    /##+\s*(?:role|persona|who\s+are\s+you)[^\n]*\n/i,
    /you\s+(?:are|'?re)\s+(?:a|an|the)\s+[^\n.]{3,80}/i,
    /act\s+as\s+(?:a|an|the)?\s*[^\n.]{3,80}/i,
    /take\s+(?:on\s+)?the\s+role\s+of\s+[^\n.]{3,60}/i,
    /pretend\s+(?:to\s+be|you(?:'re|\s+are))\s+(?:a|an|the)?\s*[^\n.]{3,60}/i,
    /imagine\s+you(?:'re|\s+are)\s+(?:a|an|the)?\s*[^\n.]{3,60}/i,
    /behave\s+(?:as|like)\s+(?:a|an|the)?\s*[^\n.]{3,60}/i,
    /respond\s+as\s+(?:a|an|the)?\s*[^\n.]{3,60}/i,
    /as\s+(?:a|an)\s+(?:senior\s+|expert\s+|professional\s+|lead\s+|principal\s+)?(?:developer|engineer|designer|writer|analyst|manager|consultant|advisor|specialist|architect|scientist|researcher|coach|teacher|instructor|mentor|expert|nutritionist|doctor|lawyer|accountant)[^\n.,]{0,40}[,\s]/i,
    /you\s+(?:are|'?re)\s+(?:an?\s+)?(?:expert|specialist|professional|senior|lead|principal)\s+[^\n.]{3,60}/i,
    /your\s+role\s+is\s+(?:to\s+be\s+)?(?:a|an|the)?\s*[^\n.]{3,60}/i,
    // Conversational role patterns
    /(?:^|\.\s+)(?:ok\s+)?so\s+I(?:'m|\s+am)\s+(?:a|an)\s+[^\n.]{3,80}/i,
    /I(?:'m|\s+am)\s+(?:a|an|the)\s+(?:UX\s+|UI\s+|senior\s+|junior\s+|lead\s+|product\s+|full[\s-]stack\s+|front[\s-]end\s+|back[\s-]end\s+|graphic\s+|web\s+|software\s+|data\s+|marketing\s+|brand\s+|high\s+school\s+|elementary\s+|freelance\s+)?(?:social\s+media\s+manager|content\s+creator|copywriter|marketer|designer|developer|writer|analyst|consultant|freelancer|entrepreneur|student|teacher|nurse|coach|trainer|manager|researcher|engineer|architect)[^\n.]{0,60}/i,
    /I(?:'m|\s+am)\s+the\s+(?:lead|manager|director|head|chief|owner|founder|admin|ceo|cto|coo|vp|lead\s+dev|team\s+lead)[^\n.]{0,60}/i,
    /I\s+specialize\s+in\s+[^\n.]{3,80}/i,
    /I\s+(?:just\s+)?(?:got|was|have\s+been)\s+(?:just\s+)?promoted\s+(?:to|as|into)\s+[^\n.]{3,80}/i,
    /I\s+work\s+(?:as|in)\s+[^\n.]{3,80}/i,
    /my\s+(?:job|role|position)\s+is\s+[^\n.]{3,80}/i,
  ],

  context: [
    /##+\s*(?:context|background|scenario|contextual\\s+information)[^\n]*\n/i,
    /(?:given\s+that|given\s+the\s+following)[^\n.]{5,150}/i,
    /in\s+the\s+context\s+of\s+[^\n.]{5,100}/i,
    /(?:assuming|assume)\s+(?:that\s+)?[^\n.]{5,120}/i,
    /background(?:\s+information)?[:\-]\s*[^\n]{5,200}/i,
    /context[:\-]\s*[^\n]{5,200}/i,
    /situation[:\-]\s*[^\n]{5,150}/i,
    /(?:I(?:'m|\s+am)|we(?:'re|\s+are))\s+(?:building|creating|developing|working\s+on|migrating|running|using)\s+[^\n.]{5,120}/i,
    /(?:my|our)\s+(?:company|team|project|app|application|product|client)\s+(?:is|has|needs|wants|is\s+looking|has\s+a)[^\n.]{3,100}/i,
    /(?:a|my|our)\s+client\s+(?:who|that|which|is|has|went)\s+[^\n.]{3,80}/i,
    /(?:the\s+)?(?:app|application|system|platform|project|product|service)\s+(?:is|has|uses|handles|processes)\s+[^\n.]{5,100}/i,
    /I(?:'m|\s+am)\s+(?:a\s+)?(?:\d+[- ]?years?[- ]?old|student|developer|beginner|professional|working)[^\n.]{0,80}/i,
    /[Aa]\s+\d+[- ]?years?[- ]?old\s+[^\n.]{3,80}/i,
    /\d+[- ]?years?[- ]?old[^\n.]{0,60}/i,
    /I\s+(?:have|need|want|work|study|use)\s+[^\n.]{5,100}/i,
    /my\s+(?:goal|objective|purpose|problem|issue|challenge)\s+is\s+[^\n.]{5,100}/i,
    /we(?:'re|\s+are)\s+(?:trying|looking|planning|aiming)\s+(?:to|for)\s+[^\n.]{5,100}/i,
    /(?:a|an)\s+[^\n.]{5,80}\s+(?:app|tool|product|platform|service)\s+(?:targeting|for|aimed\s+at|designed\s+for)[^\n.]{5,120}/i,
    /(?:app|tool|product|platform|service)\s+(?:targeting|for|aimed\s+at|designed\s+for)\s+[^\n.]{5,120}/i,
    /(?:the\s+)?(?:first-use|first\s+use|onboarding|landing|home)\s+(?:screen|page|view|experience)/i,
    // Conversational context patterns
    /(?:for|at)\s+(?:a|an)\s+(?:small|large|local|startup|tech|digital|creative)\s+[^\n.]{3,80}/i,
    /we\s+have\s+(?:a|an|about|like|around)\s+[^\n.]{3,100}/i,
    /our\s+(?:posts|content|vibe|brand|audience|customers|users|followers|community)\s+(?:have\s+been|is|are|has\s+been)[^\n.]{3,100}/i,
    /our\s+(?:vibe|brand|style|tone|voice)\s+is\s+[^\n.]{3,120}/i,
    /our\s+(?:regulars|customers|audience|users|followers)\s+(?:are|is)\s+(?:mostly|mainly|primarily)\s+[^\n.]{3,100}/i,
    /they\s+(?:hate|love|prefer|want|need|like|dislike)\s+[^\n.]{3,80}/i,
  ],

  instruction: [
    /##+\s*(?:task|your\s+task|objective|goal|instruction|request)[^\n]*\n/i,
    /(?:please\s+)?(?:write|create|generate|build|make|design|develop|draft|produce)\s+[^\n.]{3,120}/i,
    /(?:please\s+)?(?:analyze|analyse|review|evaluate|assess|examine|inspect)\s+[^\n.]{3,100}/i,
    /(?:please\s+)?(?:explain|describe|summarize|summarise|outline|elaborate|clarify)\s+[^\n.]{3,100}/i,
    /(?:please\s+)?(?:list|enumerate|identify|find|show|provide|give\s+me)\s+[^\n.]{3,100}/i,
    /(?:please\s+)?(?:translate|convert|transform|rewrite|refactor|improve|fix|correct|edit)\s+[^\n.]{3,100}/i,
    /(?:please\s+)?(?:compare|contrast|calculate|compute|solve|determine|recommend|suggest)\s+[^\n.]{3,100}/i,
    /your\s+task\s+(?:is\s+to|:)\s*[^\n.]{3,120}/i,
    /your\s+(?:goal|objective|job|mission)\s+(?:is\s+to|:)\s*[^\n.]{3,100}/i,
    /I\s+(?:need|want|would\s+like)\s+(?:you\s+to\s+)?(?:help\s+(?:me\s+)?)?(?:write|create|build|make|analyze|explain|design|generate|review)\s+[^\n.]{3,100}/i,
    /I\s+(?:want|need)\s+(?:a|an|the)?\s*[^\n.]{3,80}/i,
    /help\s+(?:me\s+)?(?:write|create|build|make|analyze|understand|design|generate|review|plan)\s+[^\n.]{3,100}/i,
    /can\s+you\s+(?:write|create|build|make|analyze|explain|design|generate|review|help)\s+[^\n.]{3,100}/i,
    // Conversational instruction patterns
    /I\s+need\s+\d+\s+[^\n.]{3,100}/i,
    /(?:can\s+you\s+)?(?:write|create|make|generate|come\s+up\s+with)\s+\d+\s+[^\n.]{3,100}/i,
    /(?:give|show)\s+me\s+\d+\s+[^\n.]{3,100}/i,
    /can\s+you\s+(?:write|create|make|generate|come\s+up\s+with)\s+[^\n?]{3,100}\?/i,
  ],

  constraint: [
    /##+\s*(?:constraints?|requirements?|rules?|limitations?|guidelines)[^\n]*\n/i,
    /(?:limit(?:ed)?\s+to|maximum|max\.?|no\s+more\s+than|at\s+most)\s+\d+[^\n.]{0,60}/i,
    /(?:minimum|min\.?|at\s+least)\s+\d+[^\n.]{0,60}/i,
    /(?:under|within|less\s+than|fewer\s+than)\s+\d+[\s-]*(?:words?|characters?|lines?|pages?|sentences?)\b/i,
    /(?:keep\s+it|keep\s+(?:the\s+)?(?:response|answer|text|output))\s+(?:under|within|brief|short|concise)[^\n.]{0,60}/i,
    /requirements?[:\-]\s*[^\n]{5,200}/i,
    /constraints?[:\-]\s*[^\n]{5,150}/i,
    /rules?[:\-]\s*[^\n]{5,150}/i,
    /(?:must|should|needs?\s+to)\s+(?:be|include|contain|have|use)\s+[^\n.]{3,100}/i,
    /[-•*]\s+(?:must|should|include|limit|keep)[^\n]{3,100}/i,
    /\d+\s+(?:strategies|methods|approaches|ways|solutions|options|ideas|tips|examples|items|points|steps|techniques|alternatives|recommendations|questions|answers|scenarios)\b/i,
    /between\s+\d+\s+and\s+\d+\s+(?:words?|characters?|lines?|sentences?)[^\n.]{0,60}/i,
  ],

  negative_constraint: [
    /(?:do\s+not|don'?t|never)\s+(?:use|include|mention|exceed|go|make|add|write|provide|give|repeat|forget|skip|ignore|use\s+passive)[^\n.]{3,80}/i,
    /(?:avoid|refrain\s+from)\s+(?:using|including|mentioning|exceeding|making|adding|writing|providing|giving|repeating|skipping|ignoring)[^\n.,]{3,80}/i,
    /(?:avoid|refrain\s+from)\s+[\w\s]+(?:words?|terms?|phrases?|language|content)[^\n.]{0,60}/i,
    /avoid\s+(?:spam|these|trigger|words?|the|following)[^\n.]{3,80}/i,
    /(?:must\s+not|should\s+not|cannot|can'?t|won'?t)\s+[^\n.]{3,100}/i,
    /(?:without\s+using|no\s+use\s+of|excluding|except\s+for|not\s+including)\s+[^\n.]{3,80}/i,
    /[-•*]\s+(?:must|should|do\s+not|avoid|exclude)[^\n]{3,100}/i,
    /nothing\s+(?:too\s+)?(?:salesy|formal|casual|technical|complex|simple|long|short|complicated|advanced|fancy|generic|corporate|cliche)[^\n.]{0,80}/i,
    /no\s+(?:fancy|special|advanced|professional|extra)\s+[^\n.]{3,60}/i,
    /(?:that'?s|this\s+is)\s+(?:exactly\s+)?what\s+I(?:'m|\s+am)\s+(?:trying\s+to\s+)?(?:get\s+away\s+from|avoid)[^\n.]{0,60}/i,
    /(?:no|without)\s+(?:hashtags|emojis|emoji|links|urls|mentions|tags|exclamation\s+marks?|all[-\s]caps)[^\n.]{0,60}/i,
  ],

  example: [
    /##+\s*(?:examples?|sample|demonstration)[^\n]*\n/i,
    /(?:for\s+)?example\s*[:\-—]\s*[^\n?!]{3,200}/i,
    /for\s+instance[:\s\-—][^\n?!]{3,200}/i,
    /e\.g\.?[:\s][^\n]{3,200}/i,
    /such\s+as[:\s][^\n]{3,150}/i,
    /like\s+this\s+example[:\s\n][^\n.]{3,200}/i,
    /sample(?:\s+input)?(?:\s+output)?[:\-]\s*[^\n]{3,200}/i,
    /input[:\-]\s*["']?[^\n]{3,150}["']?\s*(?:\n|→|->|output[:\-])/i,
    /output[:\-]\s*["']?[^\n]{3,150}/i,
    /["'][^"']{3,100}["']\s*(?:→|->|=>)\s*["'][^"']{3,100}["']/i,
    /```[\s\S]{3,500}?```/i,
    /now\s+(?:rewrite|do|apply|try)[:\s][^\n]{3,150}/i,
    // Conversational example patterns
    /here'?s\s+an?\s+example[^\n.]{0,200}/i,
    /here'?s\s+(?:my|the|a)\s+(?:rough|current|old|bad|existing|previous|draft|sample)\s+(?:version|draft|copy|text|paragraph|attempt)[^\n.]{0,100}/i,
    /(?:like|similar\s+to)\s+["'][^"']{5,150}["']/i,
    /(?:use|show|include|write|provide|give)\s+(?:a|an)?\s*example\s+[^\n.?!]{3,100}/i,
    /(?:we\s+posted|I\s+wrote|that\s+worked)\s+(?:that\s+)?(?:actually\s+)?(?:did\s+)?(?:really\s+)?(?:well|great)[^\n.]{0,100}/i,
    /that(?:'s|\s+is)?\s+(?:the\s+)?kind\s+of\s+(?:energy|vibe|tone|style|thing)[^\n.]{0,60}/i,
    /something\s+like\s+(?:(?:a|an|the)\s+)?[^\n.?]{5,80}/i,
  ],

  format: [
    /##+\s*(?:output\s+format|format|structure|response\s+format|response\s+structure)[^\n]*\n/i,
    /(?:output|return|provide|present|deliver)\s+(?:the\s+(?:result|answer|response)\s+)?(?:as|in|using)\s+[^\n.]{3,80}/i,
    /(?:format|structure|organize|arrange)\s+(?:it\s+|the\s+(?:output|response|answer|result)\s+)?(?:as|in|like)\s+[^\n.]{3,80}/i,
    /format[:\-]\s*[^\n]{3,100}/i,
    /output\s+format[:\-]\s*[^\n]{3,100}/i,
    /(?:as|in)\s+(?:a\s+)?(?:json|xml|yaml|csv|markdown|html|table|list|numbered\s+list|bullet\s+(?:points?|list)|code\s+block)\b[^\n.]{0,60}/i,
    /(?:numbered|bulleted?|ordered|unordered)\s+(?:list|format)\b[^\n.]{0,60}/i,
    /(?:use\s+)?(?:the\s+)?(?:following\s+)?(?:structure|template|esquema)[:\-]\s*[^\n]{3,150}/i,
    /(?:include|with)\s+(?:the\s+)?(?:following\s+)?(?:sections?|fields?|columns?|headers?)[:\-]\s*[^\n]{3,150}/i,
    /organize\s+(?:it|the\s+response|the\s+output)\s+(?:by|into|with)\s+[^\n.]{3,100}/i,
    /transformation?\s+pattern[:\-]\s*[^\n]{3,100}/i,
    /[^.\n]{3,50}\s*(?:->|→|=>)\s*[^.\n]{3,50}(?:\s*\.|\s*$)/i,
    /\d+\s+(?:strategies|methods|approaches|ways|solutions|options|ideas|tips|examples|items|points|steps|techniques|alternatives|recommendations|questions|answers|scenarios)\b/i,
    // Conversational format patterns
    /just\s+(?:list|give|show|write)\s+(?:them|it|the\s+\w+)\s+out[^\n.]{0,60}/i,
    /(?:just|only)\s+(?:one|a\s+single|1)\s+(?:paragraph|sentence|section|page|block)[^\n.]{0,60}/i,
    /(?:subject\s+line\s+included|include\s+(?:a\s+)?subject\s+line)[^\n.]{0,60}/i,
    /(?:nothing\s+else|no\s+(?:other|additional|extra))\s+(?:needed|required)[^\n.]{0,40}/i,
    /(?:simple|plain)\s+(?:list|format)[^\n.]{0,40}/i,
    /no\s+\w+\s+needed\b[^\n.]{0,60}/i,
    /just\s+the\s+\w+[,\s]+no\s+\w+\s+needed\b[^\n.]{0,60}/i,
    /just\s+the\s+(?:\w+\s+){0,3}(?:names?|titles?|descriptions?|questions?|answers?|lines?|points?)[^\n.]{0,80}/i,
  ],

  audience: [
    /(?:target\s+)?audience[:\-]\s*[^\n]{3,100}/i,
    /intended\s+for\s+[^\n.]{3,100}/i,
    /(?:written|designed|tailored|aimed|targeted)\s+for\s+[^\n.]{3,100}/i,
    /for\s+(?:a\s+)?(?:beginner|intermediate|advanced|expert|non-?technical|technical|junior|senior)\s+(?:audience|developer|user|reader|viewer|programmer|analyst|learner|student|professional)[^\n.]{0,60}/i,
    /(?:beginner|novice|non-?technical|layperson|general\s+public)[- ]friendly\b[^\n.]{0,60}/i,
    /(?:my\s+)?(?:audience|readers?|users?|viewers?)\s+(?:are|is|includes?|would\s+be|will\s+be)\s+[^\n.]{3,80}/i,
    /(?:the|my)\s+(?:reviewers?|readers?|evaluators?|judges?|committee)\s+(?:are|aren'?t|include|won'?t\s+all\s+be|aren'?t\s+all)[^\n.]{3,80}/i,
    /(?:reach|get)\s+out\s+to\s+[^\n.]{3,80}/i,
    /(?:my\s+)?(?:direct\s+reports?|team\s+members?|employees?)[,\s]+(?:are|have|include|all)[^\n.]{3,80}/i,
    /my\s+(?:\w+\s+){0,2}(?:students?|class|pupils?)\b[^\n.]{0,80}/i,
    /(?:my|our)\s+(?:customers?|clients?|buyers?|followers?|subscribers?)\s+(?:are|is|tend\s+to\s+be)\s+[^\n.]{3,80}/i,
    /(?:targeting|aimed\s+at|designed\s+for)\s+(?:\w+\s+){1,4}(?:who|that)\s+[^\n.]{3,80}/i,
  ],

  tone: [
    /\btone[:\-](?!\w)\s*[^\n]{3,100}/i,
    /\bstyle[:\-](?!\w)\s*[^\n]{3,100}/i,
    /\bvoice[:\-](?!\w)\s*[^\n]{3,100}/i,
    /(?:write|respond|sound|be|keep\s+(?:it|the\s+tone))\s+(?:in\s+a\s+)?(?:formal|informal|casual|professional|friendly|conversational|technical|simple|humorous|serious|empathetic|assertive|persuasive|neutral|academic|creative)\s+(?:tone|style|way|manner|voice)\b/i,
    /(?:formal|informal|casual|professional|friendly|conversational|technical|humorous|serious|empathetic|assertive|neutral|academic)\s+(?:tone|style|voice)\b/i,
    /(?:sound|be)\s+(?:formal|informal|casual|professional|friendly|conversational|humorous|serious|empathetic|assertive|neutral|academic)\b/i,
    // Conversational tone patterns
    /(?:more|less)\s+like\s+(?:something\s+)?(?:a|an)\s+[^\n.]{3,80}/i,
    /(?:sound|feel|be)\s+(?:more|less)\s+[^\n.]{3,60}/i,
    /(?:want|like|need)\s+(?:it\s+)?to\s+(?:sound|be|feel)\s+[^\n.]{3,80}/i,
    /(?:don'?t|never)\s+(?:let\s+it|make\s+it)\s+sound\s+like\s+[^\n.]{3,80}/i,
    /nothing\s+that\s+sounds?\s+like\s+[^\n.]{3,80}/i,
    /(?:it\s+)?should\s+(?:sound|feel|be)\s+[^\n.]{3,80}/i,
    /in\s+plain\s+(?:english|language|terms?)[^\n.]{0,60}/i,
    /not\s+(?:too\s+)?(?:robotic|stiff|formal|corporate|salesy|generic|scripted|fake|over[\s-]the[\s-]top)[^\n.]{0,60}/i,
  ],
};
