/**
 * Portuguese language patterns for prompt anatomy detection
 * Converted from backend/data/multilingual_patterns.yaml
 */

export const portuguesePatterns = {
  role: [
    /\bvoc[eê]\s+[eé]\s+(?:um|uma|o|a)\s+[^\n.]{3,80}/i,
    /\baja\s+como\s+(?:um|uma|o|a)?\s*[^\n.]{3,80}/i,
    /\batue\s+como\s+(?:um|uma|o|a)?\s*[^\n.]{3,80}/i,
    /\bfinja\s+(?:ser|que\s+[eé])\s+(?:um|uma|o|a)?\s*[^\n.]{3,60}/i,
    /\bimagine\s+que\s+voc[eê]\s+[eé]\s+(?:um|uma|o|a)?\s*[^\n.]{3,60}/i,
    /\bcomporte[- ]se\s+como\s+(?:um|uma|o|a)?\s*[^\n.]{3,60}/i,
    /\bresponda\s+como\s+(?:um|uma|o|a)?\s*[^\n.]{3,60}/i,
    /\bassuma\s+o\s+papel\s+de\s+[^\n.]{3,60}/i,
    /\bseu\s+papel\s+[eé]\s+(?:ser\s+)?(?:um|uma|o|a)?\s*[^\n.]{3,60}/i,
    /\bcomo\s+(?:um|uma)\s+(?:s[eê]nior\s+|especialista\s+em\s+|profissional\s+)?[^\n.,]{5,60}/i,
    /\bvoc[eê]\s+[eé]\s+(?:um|uma)?\s*(?:especialista|profissional|s[eê]nior|l[ií]der|analista|consultor|gerente|diretor|redator|advogado|controller|marketer)\s+[^\n.]{3,60}/i,
    /\b(?:voc[eê]\s+[eé]\s+)?especialista\s+em\s+[^\n.]{3,60}/i,
  ],

  context: [
    /\b(?:dado\s+que|dada\s+a\s+situa[cç][aã]o|dado\s+o\s+seguinte|considere\s+que|considerando\s+que)[^\n.]{5,150}/i,
    /\bno\s+contexto\s+de\s+[^\n.]{5,100}/i,
    /\b(?:assumindo|considerando|supondo)\s+(?:que\s+)?[^\n.]{5,120}/i,
    /\b(?:contexto|background|situa[cç][ãa]o|cenário|público)[:\-]\s*[^\n]{5,200}/i,
    /\b(?:estou|estamos)\s+(?:construindo|criando|desenvolvendo|trabalhando\s+em|migrando|usando|com)[^\n.]{5,120}/i,
    /\b(?:minha|nossa|meu|nosso|a|esta|essa)\s+(?:empresa|equipe|time|projeto|app|aplica[cç][aã]o|produto|cliente|chefe|filha?|academia|startup|loja|vaga|organização)\s+(?:[eé]|tem|est[aá]|apresentou|está\s+dando|apresenta|sofre|precisa|busca|é|são|vai)\s+[^\n.]{3,150}/i,
    /\b(?:o\s+)?(?:app|sistema|plataforma|projeto|product|servi[cç]o|aplica[cç][aã]o|software|site)\s+(?:[eé]|tem|usa|processa|gerencia|est[aá]|apresentou|está\s+dando)\s+[^\n.]{5,150}/i,
    /\b(?:trabalho|estudo|uso|atuação|histórico|setor)[:\-]\s*[^\n]{5,100}/i,
    /\b(?:meu|minha)\s+(?:objetivo|meta|problema|desafio)\s+[eé]\s+[^\n.]{5,100}/i,
    /\bestamos\s+(?:tentando|planejando|buscando|encerrando|analisando)\s+[^\n.]{5,100}/i,
    /\bsou\s+(?:um|uma)?\s*(?:estudante|desenvolvedor|iniciante|profissional|especialista|gerente|analista)[^\n.]{0,80}/i,
    /\btenho\s+\d+\s+anos[^\n.]{0,60}/i,
    /\bos\s+dados\s+mostram\s+que[^\n.]{5,150}/i,
    /\b(?:está|tá)\s+dando\s+(?:erro|problema|bug|falha)\s+no\s+[^\n.]{3,60}/i,
    /\b(?:vai|será)\s+ser\s+usado\s+(?:em|num|no|para)[^\n.]{5,100}/i,
    /\btemos\s+(?:um|uma)\s+(?:funcionário|cliente|projeto|caso|situação|vaga|software|produto|app)\s+que[^\n.]{5,150}/i,
    /\bnosso\s+(?:produto|app|cliente|ceo|time|projeto)\s+[^\n.]{5,150}/i,
    /\bpra\s+(?:a\s+|o\s+)?(?:equipe|time|empresa|projeto|uso)\b[^\n.]{0,100}/i,
    /\buso\s+(?:pessoal|profissional|interno)\b[^\n.]{0,60}/i,
    /\btentando\s+organizar\s+[^\n.]{3,100}/i,
    /\bcliente\s+que\s+sumiu\b[^\n.]{0,100}/i,
    /\bvaga\s+de\s+[^\n.]{3,100}/i,
    /\bstartup\s+de\s+[^\n.]{3,100}/i,
    /\btaxa\s+de\s+turnover\b[^\n.]{0,100}/i,
    /\btaxa\s+de\s+conversão\b[^\n.]{0,100}/i,
    /\bciclo\s+orçamentário\b[^\n.]{0,100}/i,
    /\bapp\s+de\s+delivery\b[^\n.]{0,100}/i,
    /\bplataforma\s+de\s+automação\b[^\n.]{0,100}/i,
    /\bsexta-feira\s+vai\s+ser\s+home\s+office\b/i,
    /\breativação\s+de\s+clientes\b/i,
    /\bsoftware\s+de\s+gestão\b/i,
    /\babordando\s+empresas\b/i,
    /\btreinamento\s+e\s+desenvolvimento\b/i,
    /\bprograma\s+de\s+liderança\b/i,
    /\bgestores\s+de\s+primeira\s+linha\b/i,
  ],

  instruction: [
    /\b(?:por\s+favor[,\s]+)?\b(?:escrev[ae]|cri[ae]|ger[ae]|constru[ia]|fa[cç][aoe]|desenvolv[ae]|produz[ai]|elabor[ae]|redig[ae]|proponha|suger[ei]|sugir[ae]|explic[ae]|faz|ajud[ae]|mont[ae]|redija|proponha|prepare)\s+[^\n.]{3,120}/i,
    /\b(?:por\s+favor[,\s]+)?\b(?:analis[ae]|revis[ae]|avali[ae]|examin[ae]|inspecion[ae])\s+[^\n.]{3,100}/i,
    /\b(?:por\s+favor[,\s]+)?\b(?:resum[ae]|detalh[ae]|esclare[cç][ae]|list[ae])\s+[^\n.]{3,100}/i,
    /\b(?:por\s+favor[,\s]+)?\b(?:identifiqu[ei]|encontr[ae]|mostr[ae]|forne[cç][ae]|me\s+d[eê])\s+[^\n.]{3,100}/i,
    /\b(?:por\s+favor[,\s]+)?\b(?:traduz[ai]|convert[ae]|transform[ae]|reescrev[ae]|refator[ae]|melhor[ae]|corrij[ae]|edit[ae])\s+[^\n.]{3,100}/i,
    /\b(?:por\s+favor[,\s]+)?\b(?:compar[ae]|calcul[ae]|resolv[ae]|determin[ae]|recomend[ae]|sugir[ae])\s+[^\n.]{3,100}/i,
    /\bsua\s+tarefa\s*[eé]?[:\-]?\s*(?:a\s+de\s+|para\s+)?[^\n.]{3,120}/i,
    /\bseu\s+(?:objetivo|meta|trabalho|miss[aã]o)\s*[eé]?[:\-]?\s*[^\n.]{3,100}/i,
    /\b(?:preciso|quero|gostaria)\s+(?:que\s+voc[eê]\s+)?(?:me\s+ajude\s+a\s+)?\b(?:escrev[ae]|cri[ae]|constru[ia]|analis[ae]|entender|desenvolv[ae]|ger[ae]|mont[ae]|redig[ae]|elaborar|propor|melhorar|corrigir|explicar)\s+[^\n.]{3,100}/i,
    /\bme\s+ajude\s+(?:a\s+)?(?:escrev[ae]|cri[ae]|constru[ia]|analis[ae]|entender|desenvolv[ae]|planej[ae]|mont[ae])\s+[^\n.]{3,100}/i,
    /\bpode\s+(?:escrev[ae]|cri[ae]|analis[ae]|explic[ae]|me\s+ajudar)\s+[^\n.]{3,100}/i,
    /\bpoderia\s+(?:escrev[ae]|cri[ae]|analis[ae]|explic[ae]|me\s+ajudar)\s+[^\n.]{3,100}/i,
    /\bquais\s+são\s+(?:os|as)\s+(?:riscos|chances|opções|alternativas|etapas|passos)\b[^\n.?]{3,100}/i,
    /\bresum[ao]\s+(?:a\s+)?situa[cç][ãa]o[^\n.]{0,100}/i,
    /\b(?:preciso|quero|gostaria)\s+(?:de\s+)?(?:um|uma|que)?\s*[^\n.]{3,100}/i,
    /\bme\s+d[êe]\s+\d+\s+(?:opções|ideias|exemplo|sugestões|hipóteses)/i,
    /\bprepare\s+(?:um|o)\s+relatório\b[^\n.]{3,100}/i,
    /\bo\s+que\s+(?:pode|deve|poderia)\s+ser\b/i,
    /\bo\s+que\s+voc[eê]\s+acha\b/i,
    /\bcri[ae]\s+(?:o|um)\s+cronograma\b/i,
  ],

  constraint: [
    /\blimite(?:\s+a)?|m[aá]ximo|no\s+m[aá]ximo|at[eé]\s+no\s+m[aá]ximo|m[aá]ximo\s+de\b\s+\d+[^\n.]{0,60}/i,
    /\bm[ií]nimo|pelo\s+menos|ao\s+menos|m[ií]nimo\s+de\b\s+\d+[^\n.]{0,60}/i,
    /\b(?:menos\s+de|abaixo\s+de|n[aã]o\s+mais\s+que)\s+\d+\s+(?:palavras?|caracteres?|linhas?|p[aá]ginas?|itens|minutos)[^\n.]{0,40}/i,
    /\b(?:mantenha|deixe)\s+(?:(?:a\s+)?resposta\s+)?(?:curta?|breve|concis[ao]|sucint[ao])[^\n.]{0,60}/i,
    /\b(?:requisitos?|restri[cç][oõ]es?|regras?|limite)[:\-]\s*[^\n]{5,200}/i,
    /\b(?:deve|precisa|tem\s+que|[eé]\s+necess[aá]rio)\s+(?:ser|ter|incluir|conter|usar|apresentar|durar|prefira)\s+[^\n.]{3,100}/i,
    /[-•*]\s+(?:deve|inclua|limite|keep)[^\n]{3,100}/i,
    /\d+\s+(?:estrat[eé]gias|m[eé]todos|abordagens|maneiras|solu[cç][oõ]es|op[cç][oõ]es|ideias|dicas|exemplos|itens|pontos|passos|t[eé]cnicas|alternativas|recomenda[cç][oõ]es|perguntas|respostas|cen[aá]rios|hip[oó]teses|a[cç][oõ]es)\b/i,
    /\bde\s+um\s+jeito\s+(?:simples|fácil|rápido|direto|objetivo|transparente|empático|direto|executivo|consultivo)\b/i,
    /\bresposta\s+(?:objetiva|curta|breve|detalhada)\b/i,
    /\btom\s*[eé]?[:\-]?\s*[^\n.]{3,100}/i,
  ],

  negative_constraint: [
    /\b(?:n[aã]o\s+use|n[aã]o\s+utilize|evite|n[aã]o\s+fa[cç]a|jamais|nunca|não\s+inclua|não\s+deve|não\s+pode|não\s+é\s+permitido)\s+[^\n.]{3,100}/i,
    /\b(?:sem\s+(?:usar|utilizar)|excluindo|exceto|sem\s+incluir|sem\s+ser|não\s+dependam)\s+[^\n.]{3,80}/i,
    /[-•*]\s+(?:do\s+not|don't|evite|n[aã]o|não|jamais|nunca)[^\n]{3,100}/i,
    /\bnada\s+(?:muito\s+)?(?:comercial|formal|casual|t[eé]cnico|complexo|simples|longo|curto|complicado|avan[cç]ado|extravagante|gen[eé]rico|corporativo|clich[eê])[^\n.]{0,80}/i,
    /\bsem\s+(?:suplementos?|anima[cç][oõ]es?|imagens?|exemplos?)\s*[^\n.]{0,60}/i,
    /\bn[aã]o\s+mais\s+que\s+\d+\s+parágrafos/i,
  ],

  example: [
    /\b(?:por\s+)?exemplo[:\s][^\n]{3,200}/i,
    /\bpor\s+exemplo[:\s][^\n]{3,200}/i,
    /\bp\.ex\.?[:\s][^\n]{3,200}/i,
    /\bcomo\s+(?:por\s+exemplo|este)[:\s][^\n]{3,150}/i,
    /\bcomo\s+este[:\s\n][^\n]{3,150}/i,
    /\bamostra[:\-]\s*[^\n]{3,200}/i,
    /\bentrada[:\-]\s*[^\n]{3,150}/i,
    /\bsa[ií]da[:\-]\s*[^\n]{3,150}/i,
    /["'][^"']{3,100}["']\s*(?:→|->|=>)\s*["'][^"']{3,100}["']/i,
    /```[\s\S]{3,500}?```/i,
    /\bagora\s+(?:reescreva|fa[cç]a|aplique|tente)[:\s][^\n]{3,150}/i,
    /\baqui\s+est[aá]\s+(?:um|uma)?\s*exemplo[^\n.]{0,200}/i,
    /\baqui\s+est[aá]\s+(?:meu|o|um)\s+(?:rascunho|atual|antigo|ruim|existente|anterior|exemplo)\s+(?:vers[aã]o|rascunho|c[oó]pia|texto|par[aá]grafo|tentativa)[^\n.]{0,100}/i,
    /\b(?:como|parecido\s+com)\s+["'][^"']{5,150}["']/i,
    /\b(?:use|mostre|inclua|escreva|forne[cç]a|d[eê])\s+(?:a|an)?\s*example\s+[^\n.?!]{3,100}/i,
    /\balgo\s+como\s+(?:(?:um|uma|o|a)\s+)?[^\n.?]{5,80}/i,
    /\bexemplo\s+de\s+(?:item|estrutura|formato|configura[cç][aã]o|resposta|formato|estrutura)\s*(?:esperado[a])?[:\-]/i,
    /:\s*["'][^"']{5,500}["']/i,
  ],

  format: [
    /\b(?:retorne|forneça|apresente|entregue)\s+(?:o\s+(?:resultado|resposta)\s+)?(?:como|em|usando)\s+[^\n.]{3,80}/i,
    /\b(?:formate|estruture|organize|apresente)\s+(?:(?:a|o)\s+(?:resposta|resultado))?\s+(?:como|em)\s+[^\n.]{3,80}/i,
    /\bformato\s+(?:de\s+sa[ií]da|de\s+resposta)?[:\-]\s*[^\n]{3,100}/i,
    /\b(?:como|em)\s+(?:um[a]?\s+)?(?:json|xml|yaml|csv|markdown|html|table|tabela|lista|lista\s+numerada|t[oó]picos?|se[cç][oõ]es)\b[^\n.]{0,60}/i,
    /\b(?:lista\s+(?:numerada|com\s+marcadores?|ordenada|n[aã]o\s+ordenada|em\s+t[oó]picos))\b[^\n.]{0,60}/i,
    /\b(?:use|usando)\s+(?:a\s+)?(?:seguinte\s+)?(?:estrutura|template|esquema)[:\-]\s*[^\n]{3,150}/i,
    /\b(?:inclua|com)\s+(?:as\s+)?(?:seguintes\s+)?(?:se[cç][oõ]es?|campos?|colunas?|cabe[cç]alhos?)[:\-]\s*[^\n]{3,150}/i,
    /\borganize\s+(?:(?:a|o)\s+(?:resposta|resultado))\s+(?:por|em|com)\s+[^\n.]{3,100}/i,
    /\btabela[:\-]\s*[^\n]{3,100}/i,
    /\btabela\s+with\s+colunas[:\-]/i,
    /\bse[cç][oõ]es\s+com\s+t[ií]tulo\s+em\s+negrito/i,
    /\bestrutura[:\-]\s*[^\n.]{3,100}/i,
    /\bem\s+t[oó]picos\b/i,
    /\btabela\s+com\s+colunas\b/i,
    /\b(?:em|usando)\s+t[óo]picos\b/i,
  ],

  audience: [
    /\b(?:p[uú]blico[- ])?alvo[:\-]\s*[^\n]{3,100}/i,
    /\bdestinado\s+(?:a|para)\s+[^\n.]{3,100}/i,
    /\b(?:escrito|desenvolvido|criado|projetado|direcionado)\s+para\s+[^\n.]{3,100}/i,
    /\bpara\s+(?:um[a]?\s+)?(?:iniciante|intermedi[aá]rio|avan[cç]ado|especialista|n[aã]o[- ]t[eé]cnico|t[eé]cnico|júnior|s[eê]nior)\s+[^\n.]{0,60}/i,
    /\b(?:iniciante|leigo|n[aã]o[- ]t[eé]cnico|p[uú]blico\s+geral)[- ]friendly\b[^\n.]{0,60}/i,
    /\b(?:meu|minha|nosso|nossa)\s+(?:p[uú]blico|leitores?|usu[aá]rios?|espectadores?|colaboradores|conselho)\s+(?:s[aã]o|[eé]|inclui)\s+[^\n.]{3,80}/i,
    /\bp[uú]blico\s*[eé]?[:\-]\s*[^\n]{3,100}/i,
  ],

  tone: [
    /\btom[:\-]\s*[^\n]{3,100}/i,
    /\bestilo[:\-]\s*[^\n]{3,100}/i,
    /\bvoz[:\-]\s*[^\n]{3,100}/i,
    /\b(?:escreva|responda|soe|seja|mantenha|tom|estilo)\s+[:\-]?\s*(?:um\s+tom\s+)?(?:formal|informal|casual|profissional|amig[aá]vel|conversacional|t[eé]cnico|simples|humorístico|s[eé]rio|emp[aá]tico|assertivo|persuasivo|neutro|acad[eê]mico|criativo|motivador|transparente|direto|objetivo|executivo|consultivo)\b/i,
    /\b(?:tom|estilo|voz)\s+(?:formal|informal|casual|profissional|amig[aá]vel|conversacional|t[eé]cnico|humorístico|s[eé]rio|emp[aá]tico|assertivo|neutro|acad[eê]mico)\b/i,
    /\blinguagem\s+(?:formal|informal|t[eé]cnica|simples|acess[ií]vel)\b/i,
    /\b(?:tom|escrita)\s+(?:apaixonado[a]?|encorajador[a]?|motivador[a]?)\b/i,
  ],
};
